
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author yorsh
 */
public class EstadisticasPanel extends javax.swing.JPanel {

    Gestionador gestionador;

    /**
     * Creates new form EstadisticasPanel
     */
    public EstadisticasPanel() {
        initComponents();
    }

    public EstadisticasPanel(Gestionador gestionador) {
        this.gestionador = gestionador;  // Asignación correcta del parámetro al campo de la clase
        initComponents();
        cargarEstadisticas();
        obtenerEstadisticasN2();
        lblNum3.setText(gestionador.contarBajoPesoConBurnoutPorCausa()[0] + " persona");
    }

    private void cargarEstadisticas() {
        String[] estadisticas = gestionador.calcularYObtenerEstadisticas();

        lblCausa1.setText(estadisticas[0]);
        lblCausa2.setText(estadisticas[1]);
        lblCausa3.setText(estadisticas[2]);
        lblCausa4.setText(estadisticas[3]);
    }

    private void obtenerEstadisticasN2() {
        // Supongamos que tienes un método que retorna un mapa con las estadísticas de IMC por ID de burnout.
        Map<Integer, Map<String, Integer>> estadisticas = gestionador.estadisticasImcPorIdBurnout();

// Definir los arrays para las filas y columnas de la JTable.
        String[] columnas = {"","Sobrecarga laboral", "No tener tareas completas", "Mucha presión", "Maltratado por sus superiores"};
        String[][] datos = {
            {"Bajo peso", "0", "0", "0", "0"},
            {"Peso normal", "0", "0", "0", "0"},
            {"Sobrepeso", "0", "0", "0", "0"},
            {"Obeso", "0", "0", "0", "0"}
        };

// Llenar los datos para la JTable basados en el mapa.
        for (Map.Entry<Integer, Map<String, Integer>> entry : estadisticas.entrySet()) {
            int causaId = entry.getKey(); // La causa de burnout.
            Map<String, Integer> counts = entry.getValue();

            // Asumiendo que el idBurnout corresponde directamente al índice de la columna (esto puede requerir ajustes).
            int columnaIndex = causaId - 1; // Ajusta esta línea según corresponda a cómo estén organizados tus IDs de causas.

            for (Map.Entry<String, Integer> countEntry : counts.entrySet()) {
                String imcCategoria = countEntry.getKey();
                Integer cantidad = countEntry.getValue();

                // Asumiendo que las categorías de IMC corresponden directamente a los índices de las filas.
                int rowIndex = -1;
                switch (imcCategoria) {
                    case "Bajo Peso":
                        rowIndex = 0;
                        break;
                    case "Peso normal":
                        rowIndex = 1;
                        break;
                    case "Sobrepeso":
                        rowIndex = 2;
                        break;
                    case "Obeso":
                        rowIndex = 3;
                        break;
                }
                if (rowIndex != -1 && columnaIndex >= 0 && columnaIndex < columnas.length) {
                    datos[rowIndex][columnaIndex + 1] = cantidad.toString(); // El +1 es para ajustar el índice debido a la columna de categorías IMC.
                }
            }
        }
// Crear un modelo de tabla con estos datos y nombres de columna.
        DefaultTableModel tableModel = new DefaultTableModel(datos, columnas);
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCausa1 = new javax.swing.JLabel();
        lblCausa2 = new javax.swing.JLabel();
        lblCausa3 = new javax.swing.JLabel();
        lblCausa4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblNum3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estadísticas");

        jLabel2.setText("1. Estadísticas de empleados con el síndrome según la causa.");

        jLabel3.setText("Sobrecarga laboral:");

        jLabel4.setText("No tener tareas completas:");

        jLabel5.setText("Mucha presión:");

        jLabel6.setText("Maltratado por sus superiores:");

        jLabel7.setText("3. Estadísticas de bajo peso con el síndrome atribuye la causa maltrato de los superiores.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("2. Estadísticas  por cada causa y el IMC.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCausa1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCausa3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCausa4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCausa2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCausa1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCausa2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblCausa3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCausa4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCausa1;
    private javax.swing.JLabel lblCausa2;
    private javax.swing.JLabel lblCausa3;
    private javax.swing.JLabel lblCausa4;
    private javax.swing.JLabel lblNum3;
    // End of variables declaration//GEN-END:variables
}
